### ISSUE TITLE
rest_api tycomonitor changed?

### ISSUE THREAD

**Issue by damianfm** [tkleijkers/homebridge-visonic-powerlink3#11]
Hi!

Today i was receiving a lot of errors from plugin. 

[12/1/2022 16:16:38] SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at /usr/lib/node_modules/homebridge-visonic-powerlink3/node_modules/visonic-powerlink3/index.js:84:32
    at Request._callback (/usr/lib/node_modules/homebridge-visonic-powerlink3/node_modules/visonic-powerlink3/index.js:309:4)
    at Request.self.callback (/usr/lib/node_modules/homebridge-visonic-powerlink3/node_modules/request/request.js:185:22)
    at Request.emit (node:events:390:28)
    at Request.<anonymous> (/usr/lib/node_modules/homebridge-visonic-powerlink3/node_modules/request/request.js:1154:10)
    at Request.emit (node:events:390:28)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/homebridge-visonic-powerlink3/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (node:events:509:28)
    at IncomingMessage.emit (node:events:402:35)
    at endReadableNT (node:internal/streams/readable:1343:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)

Debuging errors, i found that "https://visonic.tycomonitor.com/rest_api/8.0/panel/login" shows me a "404", and i tried to change to "https://visonic.tycomonitor.com/rest_api/9.0/panel/login" and it runs ok. 

So, i decide to **change "self.restVersion" from 8.0 to 9.0** in /usr/lib/node_modules/homebridge-visonic-powerlink3/node_modules/visonic-powerlink3/index.js and now it's running ok

Someone else with this error?

**Comment by StuFull** [comment]
I’ve got the same problem.  Can you explain a bit more about how you made the change please??

Thx.

**Comment by StuFull** [comment]
I had the same problem.

The fix above works - Thanks.

**Comment by damianfm** [comment]
You're welcome. Please @tkleijkers could you please confirm this "patch"?. Thanks

**Comment by witchdrash** [comment]
Nice work around, let me give that a shot

**Comment by tkleijkers** [comment]
Nice work. Seems like Visonic updated the API. I updated the repository and will push an update to npm.

**Comment by JSVarga** [comment]
I'm frustratingly still on the old Visonic monitoring connection with a Panel Name and PIN. Any chance the previous version, possibly v1, could me made available to reinstall for backward compatibility. Keep hassling my alarm company but not much luck yet.

**Comment by YecheT** [comment]
The fix above works for me as well - Thanks.

**Comment by nitaybz** [comment]
@tkleijkers are you intending to push a fix for that? I saw you already made the fix (on Github only) for the visonic-powerlink3 lib. is it possible to push to npm and update current plugin to use that version?

**Comment by tkleijkers** [comment]
@nitaybz Update has been pushed to NPM
