### ISSUE TITLE
Plugin breaks homebridge. 

### ISSUE THREAD

**Issue by Raptor0014** [tkleijkers/homebridge-visonic-powerlink3#23]
As per title plugin is breaking homebridge and forcing homebridge to constantly try and restart.  Had to disable for now. 

Get an error message saying not running and to view logs. 

Logs says:

syntaxerror:%20Unexpected%20token%20'%3C',%20%22%3Chtml%3E%20...%20is%20not%20valid%20JSON%20at%20JSON%20parse%20(%E2%80%B9anonymous%20%E2%80%BA)%0Aat%20/var/lib/homebridge/node_modules/homebridge-visonic-powerlink3/node_module%0As/visonic-powerlink3/index.js:84:32%0Aat%20Request._callback%20(/var/lib/homebridge/node_modules/homebridge-visonic-pow%0Aerlink3/node_modules/visonic-powerlink3/index.js:334:4)%0Aat%20Request.self.callback%20(/var/lib/homebridge/node_modules/homebridge-visonic%0A-powerlink3/node_modules/request/request.js:185:22)%0Aat%20Request.emit%20(node:events:%20519:28)%0Aat%20Request.%20%E2%80%B9anonymous%3E%20(/var/lib/homebridge/node_modules/homebridge-visonic-p%0Aowerlink3/node_modules/request/request.js:1154:10)%0Aat%20Request.emit%20(node:events:519:28)%0Aat%20IncomingMessage.%20%E2%80%B9anonymous%3E%20(/var/lib/homebridge/node_modules/homebridge-v%0Aisonic-powerlink3/node_modules/request/request.js:1076:12)%0Aat%20Object.onceWrapper%20(node:events:%20633:28)%20at%20IncomingMessage.emit%20(node:events:531:35)

![IMG_1902](https://github.com/user-attachments/assets/0e8bec7b-a90e-4d35-94e7-21e6c553f849)

**Comment by damianfm** [comment]
I have the same error since yesterday, Homebridge v1.8.4 and Homebridge UI v4.58.0

**Comment by Raptor0014** [comment]
I wonder if the Visonic.tycomonitor.com server is down?

**Comment by Raptor0014** [comment]
This has happened again and this is the error I get in the log.

[05/02/2025, 19:16:37] SyntaxError: Unexpected token '<', "<html>
<h"... is not valid JSON
    at JSON.parse (<anonymous>)
    at /var/lib/homebridge/node_modules/homebridge-visonic-powerlink3/node_modules/visonic-powerlink3/index.js:84:32
    at Request._callback (/var/lib/homebridge/node_modules/homebridge-visonic-powerlink3/node_modules/visonic-powerlink3/index.js:334:4)
    at Request.self.callback (/var/lib/homebridge/node_modules/homebridge-visonic-powerlink3/node_modules/request/request.js:185:22)
    at Request.emit (node:events:524:28)
    at Request.<anonymous> (/var/lib/homebridge/node_modules/homebridge-visonic-powerlink3/node_modules/request/request.js:1154:10)
    at Request.emit (node:events:524:28)
    at IncomingMessage.<anonymous> (/var/lib/homebridge/node_modules/homebridge-visonic-powerlink3/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (node:events:638:28)
    at IncomingMessage.emit (node:events:536:35)
[05/02/2025, 19:16:37] Got SIGTERM, shutting down Homebridge...

**Comment by tkleijkers** [comment]
Please verify if the server from visonic is not returning an error.

**Comment by Raptor0014** [comment]
No the server from Visonic is fine as my Visonic app works fine.

**Comment by Asafrov** [comment]
Same issue here also. the Visonic app is working fine yet the homebridge plugin crashes. any way to fix this issue?

**Comment by tkleijkers** [comment]
As I don't have a test setup anymore, I cannot check. If someone can fix it and creates a PR I will pull.
